# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
  # aliased to a recent 5.5.x version
  - 5.4
  # hhvm
  #- hhvm

# omitting "script:" will default to phpunit
# use the $DB env variable to determine the phpunit.xml to use
before_script:
  - composer install --no-interaction
  - mkdir -p build/logs

script:
  - vendor/bin/phpunit --configuration test/phpunit.xml --coverage-clover build/logs/clover.xml test

after_success:
    - CODECLIMATE_REPO_TOKEN=84c2f91a71d1746f8b0c451ce123dc5d8aadcba9ddac53983d0ec5c5b6dae775 ./vendor/bin/test-reporter

# configure notifications (email, IRC, campfire etc)
notifications:
  email: "ashley@zf4.biz"

